<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="10.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Refit" Version="14.0.1" />
        <PackageReference Include="Refit.HttpClientFactory" Version="14.0.1" />
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="Data\servicetypes.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Scheduler.Domain\Scheduler.Domain.csproj" />
      <ProjectReference Include="..\Scheduler.Application\Scheduler.Application.csproj" />
    </ItemGroup>

</Project>
